function sendSampleData()
data = sampleData(123, 'sampleData', 42.5, ["tag1", "tag2", "tag3"]);

dataStruct = struct(...
    'id',        data.id, ...
    'name',      data.name, ...
    'value',     data.value, ...
    'timestamp', char(data.timestamp), ...
    'tags',      {data.tags} ...
    );

options = weboptions(...
    'MediaType', 'application/json', ...
    'ContentType', 'json', ...
    'CharacterEncoding', 'UTF-8' ...
    );

for i = 1:10
    try
        response = webwrite('http://localhost:9012/cmds/proxies/matlab', dataStruct, options);
        disp(response);
    catch ME
        disp(ME.message);
    end
end
end